---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: submariner-engine
subjects:
  - kind: ServiceAccount
    name: submariner-engine
roleRef:
  kind: Role
  name: submariner-engine
  apiGroup: rbac.authorization.k8s.io
